# Generated by Django 3.2.6 on 2021-08-15 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default=0, max_length=20)),
            ],
            options={
                'db_table': 'social_platform',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('birthdate', models.DateTimeField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('social', models.ForeignKey(blank=True, default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='accountapp.socialplatform')),
            ],
        ),
    ]
