# Generated by Django 3.2.6 on 2021-08-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_auto_20210816_0601'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appuser',
            table='user',
        ),
    ]
