# Generated by Django 3.2.6 on 2021-08-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_alter_appuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.BigIntegerField(db_column='user_id', primary_key=True, serialize=False),
        ),
    ]
