# Generated by Django 3.2.6 on 2021-08-21 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailboxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigIntegerField(db_column='letter_id', primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sender', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[('RED', 'Red'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange')], max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='mailboxapp.mailbox')),
            ],
            options={
                'db_table': 'letter',
            },
        ),
    ]
