# Generated by Django 3.2.6 on 2021-08-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigIntegerField(db_column='letter_id', primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sender', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[('RED', 'Red'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange')], max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
