# Generated by Django 3.2.6 on 2021-09-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailboxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(db_column='letter_id', primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sender', models.CharField(max_length=20)),
                ('receiver', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('checked', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='mailboxapp.mailbox')),
            ],
            options={
                'db_table': 'letter',
            },
        ),
    ]
