# Generated by Django 3.2.6 on 2021-08-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='id',
            field=models.BigAutoField(db_column='letter_id', primary_key=True, serialize=False),
        ),
    ]
