# Generated by Django 3.2.6 on 2021-08-19 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailboxapp', '0001_initial'),
        ('letterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='mailboxapp.mailbox'),
        ),
    ]
