# Generated by Django 3.2.6 on 2021-08-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0002_letter_mailbox'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='letter',
            table='letter',
        ),
    ]
