# Generated by Django 3.2.6 on 2021-08-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='mailbox_link',
            field=models.URLField(null=True),
        ),
    ]
