# Generated by Django 3.2.6 on 2021-08-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mailbox',
            table='mailbox',
        ),
    ]
