# Generated by Django 3.2.6 on 2021-08-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxapp', '0003_alter_mailbox_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='key',
            field=models.CharField(db_column='mailbox_key', max_length=50, null=True),
        ),
    ]
