# Generated by Django 3.2.6 on 2021-08-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxapp', '0002_alter_mailbox_id'),
        ('mailboxapp', '0004_alter_mailbox_key'),
    ]

    operations = [
    ]
